import{H as g}from"./assets/vendor-C2YCf6JV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))u(n);new MutationObserver(n=>{for(const e of n)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&u(s)}).observe(document,{childList:!0,subtree:!0});function r(n){const e={};return n.integrity&&(e.integrity=n.integrity),n.referrerPolicy&&(e.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?e.credentials="include":n.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function u(n){if(n.ep)return;n.ep=!0;const e=r(n);fetch(n.href,e)}})();const b=g.template({1:function(l,t,r,u,n){var e,s=t??(l.nullContext||{}),i=l.hooks.helperMissing,a="function",c=l.escapeExpression,o=l.lookupProperty||function(m,p){if(Object.prototype.hasOwnProperty.call(m,p))return m[p]};return`  <li>
    <a href='`+c((e=(e=o(r,"url")||(t!=null?o(t,"url"):t))!=null?e:i,typeof e===a?e.call(s,{name:"url",hash:{},data:n,loc:{start:{line:3,column:13},end:{line:3,column:20}}}):e))+`' target='_blank' rel='noopener noreferrer'>
      <article>
        <img src='`+c((e=(e=o(r,"urlToImage")||(t!=null?o(t,"urlToImage"):t))!=null?e:i,typeof e===a?e.call(s,{name:"urlToImage",hash:{},data:n,loc:{start:{line:5,column:18},end:{line:5,column:32}}}):e))+`' alt='' width='480' />
        <h2>`+c((e=(e=o(r,"title")||(t!=null?o(t,"title"):t))!=null?e:i,typeof e===a?e.call(s,{name:"title",hash:{},data:n,loc:{start:{line:6,column:12},end:{line:6,column:21}}}):e))+`</h2>
        <p>Posted by: `+c((e=(e=o(r,"author")||(t!=null?o(t,"author"):t))!=null?e:i,typeof e===a?e.call(s,{name:"author",hash:{},data:n,loc:{start:{line:7,column:22},end:{line:7,column:32}}}):e))+`</p>
        <p>`+c((e=(e=o(r,"description")||(t!=null?o(t,"description"):t))!=null?e:i,typeof e===a?e.call(s,{name:"description",hash:{},data:n,loc:{start:{line:8,column:11},end:{line:8,column:26}}}):e))+`</p>
      </article>
    </a>
  </li>
`},compiler:[8,">= 4.3.0"],main:function(l,t,r,u,n){var e,s=l.lookupProperty||function(i,a){if(Object.prototype.hasOwnProperty.call(i,a))return i[a]};return(e=s(r,"each").call(t??(l.nullContext||{}),t,{name:"each",hash:{},fn:l.program(1,n,0),inverse:l.noop,data:n,loc:{start:{line:1,column:0},end:{line:12,column:9}}}))!=null?e:""},useData:!0}),P="4330ebfabc654a6992c2aa792f3173a3",v="https://newsapi.org/v2",L={headers:{Authorization:P}};class q{constructor(){this.searchQuery="",this.page=1}fetchArticles(){const t=`${v}/everything?q=${this.searchQuery}&language=en&pageSize=5&page=${this.page}`;return fetch(t,L).then(r=>r.json()).then(({articles:r})=>(this.incrementPage(),r))}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}class w{constructor({selector:t,hidden:r=!1}){this.refs=this.getRefs(t),r&&this.hide()}getRefs(t){const r={};return r.button=document.querySelector(t),r.label=r.button.querySelector(".label"),r.spinner=r.button.querySelector(".spinner"),r}enable(){this.refs.button.disabled=!1,this.refs.label.textContent="Показать ещё",this.refs.spinner.classList.add("is-hidden")}disable(){this.refs.button.disabled=!0,this.refs.label.textContent="Загружаем...",this.refs.spinner.classList.remove("is-hidden")}show(){this.refs.button.classList.remove("is-hidden")}hide(){this.refs.button.classList.add("is-hidden")}}console.log("Hello world");const h={searchForm:document.querySelector(".js-search-form"),articlesContainer:document.querySelector(".js-articles-container")},d=new w({selector:'[data-action="load-more"]',hidden:!0}),f=new q;h.searchForm.addEventListener("submit",A);d.refs.button.addEventListener("click",y);function A(l){if(l.preventDefault(),f.query=l.currentTarget.elements.query.value,f.query==="")return alert("Введи что-то нормальное");d.show(),f.resetPage(),O(),y()}function y(){d.disable(),f.fetchArticles().then(l=>{S(l),d.enable()})}function S(l){h.articlesContainer.insertAdjacentHTML("beforeend",b(l))}function O(){h.articlesContainer.innerHTML=""}
//# sourceMappingURL=index.js.map
